version: '3.8'
services:
    app:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend/src:/app/src
        ports:
            - '3000:3000'
        stdin_open: true
        